<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGCNvDUg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGCNvDUg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGCNvDUg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGCNvDUg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGCNvDUg\App_KernelDevDebugContainer([
    'container.build_hash' => 'GCNvDUg',
    'container.build_id' => '7aedf02a',
    'container.build_time' => 1624543345,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGCNvDUg');
