<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'api_user' => [[], ['_controller' => 'App\\Controller\\ApiController::index'], [], [['text', '/api/user']], [], []],
    'demande' => [[], ['_controller' => 'App\\Controller\\DemandeController::index'], [], [['text', '/demande']], [], []],
    'entreprise' => [[], ['_controller' => 'App\\Controller\\EntrepriseController::index'], [], [['text', '/entreprise']], [], []],
    'projet' => [[], ['_controller' => 'App\\Controller\\ProjetController::index'], [], [['text', '/projet']], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], []],
    'soutenance' => [[], ['_controller' => 'App\\Controller\\SoutenanceController::index'], [], [['text', '/soutenance']], [], []],
    'user' => [[], ['_controller' => 'App\\Controller\\UserController::index'], [], [['text', '/user']], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    'api_login_check' => [[], [], [], [['text', '/api/login_check']], [], []],
];
