<?php

namespace ContainerGCNvDUg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEntrepriseControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\EntrepriseController' shared autowired service.
     *
     * @return \App\Controller\EntrepriseController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\EntrepriseController'] = $instance = new \App\Controller\EntrepriseController();

        $instance->setContainer(($container->privates['.service_locator.W9y3dzm'] ?? $container->load('get_ServiceLocator_W9y3dzmService'))->withContext('App\\Controller\\EntrepriseController', $container));

        return $instance;
    }
}
