<?php

namespace ContainerGCNvDUg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSoutenanceRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\SoutenanceRepository' shared autowired service.
     *
     * @return \App\Repository\SoutenanceRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\SoutenanceRepository'] = new \App\Repository\SoutenanceRepository(($container->services['doctrine'] ?? $container->load('getDoctrineService')));
    }
}
